PTL_PATH ?= .

ifeq ($(TARGET),)
$(error You need to define target: $(MAKE) TARGET=(msp430|avr|stm32))
endif

ifeq ($(TARGET), avr)
MCU = atmega168
TARGET_FLAGS = -mmcu=$(MCU)
endif

ifeq ($(TARGET), msp430)
MCU = msp430g2553
TARGET_FLAGS = -mmcu=$(MCU)
endif

ifeq ($(TARGET), stm32)
LIBOPENCM3_PATH = ../libopencm3
CROSS_COMPILE = arm-linux-gnueabi-
GCC_VER = -4.4
TARGET_INCLUDE = -I$(LIBOPENCM3_PATH)/include
TARGET_FLAGS = -mthumb -mcpu=cortex-m3
TARGET_CFLAGS = $(TARGET_FLAGS) -D__STM32__ -DSTM32F1
TARGET_LDFLAGS = $(TARGET_FLAGS) --static -nostdlib -nostartfiles -Tstm32/f1/stm32f100x6.ld -Wl,--gc-sections \
    -Wl,--build-id=none
LDLIBS = -L$(LIBOPENCM3_PATH)/lib -lopencm3_stm32f1
endif

CROSS_COMPILE ?= $(TARGET)-
GCC_VER ?=
CC = $(CROSS_COMPILE)gcc$(GCC_VER)
CXX = $(CROSS_COMPILE)g++$(GCC_VER)
OBJDUMP = $(CROSS_COMPILE)objdump
OBJCOPY = $(CROSS_COMPILE)objcopy

CFLAGS ?= -Os -g
ALL_INCLUDE = -I$(PTL_PATH)/include/ $(TARGET_INCLUDE) $(INCLUDE)
TARGET_CFLAGS  ?= $(TARGET_FLAGS)
TARGET_LDFLAGS ?= $(TARGET_FLAGS)
ALL_CFLAGS = $(ALL_INCLUDE) $(TARGET_CFLAGS) $(CFLAGS)
ALL_CXXFLAGS = $(ALL_CFLAGS) -fno-exceptions
LDFLAGS = $(TARGET_LDFLAGS) -Wl,-Map=$@.map,--cref
TARGETDIR = bin-$(TARGET)


$(TARGETDIR)/%.o: %.cpp
	mkdir -p $(TARGETDIR)
	$(CXX) $(ALL_CXXFLAGS) -c $^ -o $@

$(TARGETDIR)/%.o: %.c
	mkdir -p $(TARGETDIR)
	$(CXX) $(ALL_CXXFLAGS) -c $^ -o $@

.PRECIOUS: $(TARGETDIR)/%.hex $(TARGETDIR)/%.bin

ifeq ($(TARGET), msp430)
flash-%: $(TARGETDIR)/%
	mspdebug rf2500 "prog $^"
endif

ifeq ($(TARGET), avr)
$(TARGETDIR)/%.hex: $(TARGETDIR)/%
	$(OBJCOPY) -O ihex -R .eeprom $^ $@
	$(OBJCOPY) -j .eeprom --set-section-flags=.eeprom="alloc,load" --change-section-lma .eeprom=0 --no-change-warnings -O ihex $^ $^.eep || exit 0

flash-%: $(TARGETDIR)/%.hex
	avrdude -p m328p -c arduino -P/dev/ttyUSB0 -b57600 -D -Uflash:w:$^
endif

ifeq ($(TARGET), stm32)
$(TARGETDIR)/%.bin: $(TARGETDIR)/%
	$(OBJCOPY) -O binary $^ $@

flash-%: $(TARGETDIR)/%.bin
	st-flash write $^ 0x8000000
endif


disasm-%: $(TARGETDIR)/%
	$(OBJDUMP) -dSt --demangle $^ >$^.disasm

all:

clean:
	rm -f $(TARGETDIR)/*.o
